export const ACTION_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const ACTION_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const ACTION_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const ACTION_LOGOUT = 'USER_LOGOUT';
export const ACTION_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';